### PR TITLE
[android][discoverReaders] Fix promise resolution

### LINKED ISSUE #371: `discoverReaders` never resolves when successfull
**Describe the bug**

When I call `discoverReaders`, I **never receive the resolved promise** of this call even though I am receiving `didUpdateDiscoveredReaders` callback event.

However this is a problem because if I call `cancelDiscovering` and then try to call `discoverReaders` again, then I will this time get my promise resolved with and `error`.

```
{
    "code": "READER_ERROR.READER_BUSY",
    "message": "Could not execute discoverReaders because the SDK is busy with another command: discoverReaders."
}
```
**To reproduce**

(If it is useful)

- Device: Galaxy Tab S5e
- "react-native": "0.63.4"
- Gradle Plugin version 4.0.0
- Gradle version: 6.5
-  buildToolsVersion = "31.0.0"
- minSdkVersion = 21
-  compileSdkVersion = 31
- targetSdkVersion = 31
- supportLibVersion = "28.0.0"

### PR DESCRIPTION
**Pull request by billfinn-stripe**
## Summary

Update Android's `discoverReaders` to properly resolve the passed in promise.

Also, fix an issue where our `discoverCancelable` could get stuck in a non-null
state, which caused any subsenquent calls to `discoverReaders` to fail with a
"busy" error.

PR is best reviewed commit-by-commit.

## Motivation

Fixes #371.

## Testing

- [x] I tested this manually
- [ ] I added automated tests

## Documentation

Select one:

- [ ] I have added relevant documentation for my changes.
- [x] This PR does not result in any developer-facing changes.

TBD updating a CHANGELOG.

### CODE REVIEW

File: android/src/main/java/com/stripeterminalreactnative/listener/RNDiscoveryListener.kt [hunk 1]
```diff
@@ -1,20 +1,22 @@
...
 import com.stripeterminalreactnative.mapFromReaders
 import com.stripeterminalreactnative.nativeMapOf
 
-class RNDiscoveryListener(
+internal class RNDiscoveryListener(
     private val context: ReactApplicationContext,
+    promise: Promise,
     private val onDiscoveredReaders: (readers: List<Reader>) -> Unit,
-) : DiscoveryListener, Callback {
+) : DiscoveryListener, NoOpCallback(promise) {
```
Comment (rv-stripe) [inline android/src/main/java/com/stripeterminalreactnative/listener/RNDiscoveryListener.kt:20]: This might be better as a delegate: `Callback by NoOpCallback(promise)` rather than opening and extending the class.

**Review by rv-stripe — APPROVED** [review]
Minor comment, but looks good

File: android/src/main/java/com/stripeterminalreactnative/listener/RNDiscoveryListener.kt (hunk 1 above)
Comment (billfinn-stripe) [reply android/src/main/java/com/stripeterminalreactnative/listener/RNDiscoveryListener.kt:20]: Sounds good. I created a delegate variable on the class. Thanks for the suggestion!
